@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

title Components for Container TodoMVC

Person(user, "User", "A user with a list of todos.")
Container_Boundary(todomvc_app, "TodoMVC") {
  Component(todomvc, "Application", "Java, JavaFX", "Integrates Backend and Frontend.")
  Component(todomvc_frontend, "Frontend", "Java, JavaFX", "Creates commands and queries and displays query results.")
  Component(todomvc_backend, "Backend", "Java", "Handles commands and queries.")
  Component(todomvc_contract, "Contract", "Java", "Defines commands, queries and common data.")
}
ContainerDb(filesystem, "Filesystem Data Store", "JSON", "Stores JSON-File with todo list.")

Rel(user, todomvc, "Uses", "JavaFX")
Rel(todomvc, todomvc_frontend, "Uses", "Java, Library")
Rel(todomvc, todomvc_backend, "Uses", "Java, Library")
Rel(todomvc_backend, todomvc_contract, "Uses", "Java, Library")
Rel(todomvc_frontend, todomvc_contract, "Uses", "Java, Library")
Rel(todomvc_backend, filesystem, "Load/Store", "JSON")
@enduml
