@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title Containers for System TodoMVC

Person(user, "User", "A user with a list of todos.")
System_Boundary(todomvc_system, "TodoMVC") {
  Container(todomvc_app, "Application", "Java, JavaFX", "Allows users to view and edit their todo list.")
  ContainerDb(filesystem, "Filesystem Data Store", "JSON", "Stores JSON-File with todo list.")
}

Rel(user, todomvc_app, "Uses", "JavaFX")
Rel(todomvc_app, filesystem, "Load/Store", "JSON")
@enduml
