@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

title System Context for TodoMVC

Person(user, "User", "A user with a list of todos.")
System(todomvc, "TodoMVC", "Allows users to view and edit their todo list.")

Rel(user, todomvc, "Uses", "JavaFX")
@enduml
