/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.muspellheim.todomvc.frontend;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
